#!/bin/bash

# Name for the database
DB_NAME=MovieRecommender

# Drop and create the database - may generate warning if the database doesn't exist yet
# Note - this deletes the entire database
dropdb "$DB_NAME"
createdb "$DB_NAME"

# Create the tables
CREATE_TABLES='CREATE TABLE "User" (
  id SERIAL PRIMARY KEY,
  username VARCHAR(25) NOT NULL UNIQUE,
  hash VARCHAR(128) NOT NULL,
  full_name VARCHAR(255)
);
CREATE TABLE "Movie" (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  api_id VARCHAR(20) NOT NULL
);
CREATE TABLE "Pair" (
  user_a SERIAL REFERENCES "User"(id),
  user_b SERIAL REFERENCES "User"(id),
  PRIMARY KEY (user_a, user_b)
);
CREATE TABLE "Preference" (
  "user" SERIAL REFERENCES "User"(id),
  movie SERIAL REFERENCES "Movie"(id),
  rating int NOT NULL,
  PRIMARY KEY ("user", movie)
);
CREATE TABLE "AuthToken" (
  token VARCHAR(128) PRIMARY KEY,
  "user" SERIAL REFERENCES "User"(id) NOT NULL,
  valid BOOLEAN NOT NULL
);'
psql -d "$DB_NAME" -c "$CREATE_TABLES"
